config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/auth/google_oauth2/callback" => 'sessions#create'

  resources :users, only: [:new, :create, :show] do
    resources :expenses
    get 'expenses/:id/next', to: 'expenses#next'
  end

  resources :productions, only: [:show, :new, :create, :edit, :update] do
    resources :expenses, only: [:show, :new, :create]
  end

  resources :expenses, only: [:update, :destroy]

  get 'pending_expenses', to: 'expenses#pending'
  get 'approved_expenses', to: 'expenses#approved'
  get 'not_approved_expenses', to: 'expenses#not_approved'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :expenses
  has_many :productions, through: :expenses

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }, uniqueness: true

  has_secure_password

  def self.find_or_create_by_omniauth(auth_hash)
    self.find_or_create_by(uid: auth_hash["uid"]) do |u|
      u.uid = auth_hash["uid"]
      u.name = auth_hash["info"]["name"]
      u.email = auth_hash["info"]["email"]
      u.password = SecureRandom.hex
    end
  end

  def owns_expense(expense)
    self.expenses.include?(expense)
  end

  def last_production
    if self.expenses.any?
      self.expenses.last.production
    end
  end

  def last_production_name
    if last_production
      self.last_production.name
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show]

  def show
    @productions = Production.all if current_user.admin
    respond_to do |f|
      f.html
      f.json {render json: current_user}
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :role, :password, :password_confirmation, :admin)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin.html.erb
<% if current_user.admin == true %>

  <p><strong>Productions</strong></p>

  <%= render partial: "productions/table", locals: {productions: @productions } %>

  <%= link_to "Create New Production", new_production_path %>

  <br></br>

  <p><strong>View all expenses by status:</strong> <%= link_to "Pending", pending_expenses_path %> | <%= link_to "Approved", approved_expenses_path %> | <%= link_to "Not Approved", not_approved_expenses_path %></p>

  <br></br>

<% end %>

app/views/users/_errors.html.erb
<% if user.errors.any? %>
  <ul>
    <% user.errors.full_messages.each do |message| %>
      <li style="color:red;"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: "shared/errors", locals: {object: @user} %>

<%= form_for @user do |u| %>
  <%= u.label "Name" %>
  <%= u.text_field :name %><br></br>

  <%= u.label "Email" %>
  <%= u.email_field :email %><br></br>

  <%= u.label "Password" %>
  <%= u.password_field :password %><br></br>

  <%= u.label "Confirm Password" %>
  <%= u.password_field :password_confirmation %><br></br>

  <%= u.label :admin %>
  <%= u.check_box :admin %><br></br>

  <%= u.submit %>

<% end %>

app/views/users/show.html.erb
<h1 data-id="<%=current_user.id%>">Hello <%= current_user.name %>!</h1>
<br>

<p>Welcome back to Film Budget Helper! How can I help you?</p>

<%= link_to "View My Expenses", user_expenses_path(current_user), class: "all-expenses", :"data-id" => current_user.id %><br>
<%= link_to "Create New Expense", new_user_expense_path(current_user), class: "new-expense", :"data-id" => current_user.id %><br>
<%= link_to "Create New Expense for #{current_user.last_production_name}", new_production_expense_path(current_user.last_production), class: "new-expense", :"data-id" => current_user.id if current_user.last_production %>