config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/auth/google_oauth2/callback" => 'sessions#create'

  resources :users, only: [:new, :create, :show] do
    resources :expenses
    get 'expenses/:id/next', to: 'expenses#next'
  end

  resources :productions, only: [:show, :new, :create, :edit, :update] do
    resources :expenses, only: [:show, :new, :create]
  end

  resources :expenses, only: [:update, :destroy]

  get 'pending_expenses', to: 'expenses#pending'
  get 'approved_expenses', to: 'expenses#approved'
  get 'not_approved_expenses', to: 'expenses#not_approved'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/production.rb
class Production < ApplicationRecord
  has_many :expenses
  has_many :users, through: :expenses

  validates :name, presence: true
  validates :budget, presence: true
  validates :budget, numericality: { greater_than: 100 }

  def dollar_budget
      "$" + ("%.2f" % self.budget)
  end

  def approved_expenses
    self.expenses.approved
  end

end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  before_action :require_login
  before_action :set_production, only: [:show, :edit, :update]
  before_action :require_admin

  def show
    render json: @production
  end

  def new
    @production = Production.new
  end

  def create
    @production = Production.new(production_params)
    if @production.save
      redirect_to production_path(@production.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @production.update(production_params)
      redirect_to production_path(@production.id)
    else
      render :edit
    end
  end

  private

  def set_production
    @production = Production.find(params[:id])
  end

  def production_params
    params.require(:production).permit(:name, :budget)
  end

end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/views/productions/_form.html.erb
<%= form_for production do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :budget %>
  <%= f.number_field :budget, min: 0.01, max: 999999.99, step: 0.01 %><br>

  <%= f.submit %>
<% end %>

app/views/productions/_table.html.erb
<table class="table">
  <tr>
    <td><strong>Name</strong></td>
    <td><strong>Budget</strong></td>
    <td><strong>Link</strong></td>
  </tr>
<% productions.find_each do |production| %>
  <tr>
  <td><%= production.name %></td>
  <td><%= production.dollar_budget %></td>
  <td><%= link_to "See details", production_path(production.id) %></td>
  </tr>
<% end %>
</table>

app/views/productions/edit.html.erb
<h1> Edit Production </h1>

<%= render partial: "shared/errors", locals: {object: @production} %>

<%= render partial: "form", locals: {production: @production} %>

app/views/productions/new.html.erb
<h1> New Production </h1>

<%= render partial: "shared/errors", locals: {object: @production} %>

<%= render partial: "form", locals: {production: @production} %>

app/views/productions/show.html.erb
<h1><%= @production.name %></h1><br></br>

<h2>Budget: <%= @production.dollar_budget %></h2><br></br>

<%= render partial: "expenses/table", locals: {expenses: @production.approved_expenses} %><br></br>

<p><%= link_to "Edit Production", edit_production_path(@production.id) %> | <%= link_to "Home", user_path(current_user) %></p>