config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  get "/auth/google_oauth2/callback" => 'sessions#create'

  resources :users, only: [:new, :create, :show] do
    resources :expenses
    get 'expenses/:id/next', to: 'expenses#next'
  end

  resources :productions, only: [:show, :new, :create, :edit, :update] do
    resources :expenses, only: [:show, :new, :create]
  end

  resources :expenses, only: [:update, :destroy]

  get 'pending_expenses', to: 'expenses#pending'
  get 'approved_expenses', to: 'expenses#approved'
  get 'not_approved_expenses', to: 'expenses#not_approved'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Film Budget Helper", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user %>
      <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "My Expenses", user_expenses_path(current_user), class: "nav-link all-expenses", :"data-id" => current_user.id %></li>
      <li class="nav-item"><%= link_to "New Expense", new_user_expense_path(current_user), class: "nav-link new-expense", :"data-id" => current_user.id %></li>
      <li class="nav-item"><%= link_to "Log out", logout_path, class: "nav-link" %></li>
      <% else %>
      <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Sign up", new_user_path, class: "nav-link"  %></li>
      <li class="nav-item"><%= link_to 'Log in with Google', '/auth/google_oauth2', class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilmBudgetHelper</title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="container" role="main">
      <%= render 'layouts/navigation' %>
      <br>
      <div id="errors">
        <% if flash.any? %>
            <% flash.each do |key, value| %>
              <div class="alert alert-info alert-<%= key %>"><%= value %></div>
            <% end %>
        <% end %>
      </div>
      <div id="app-container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>